### ISSUE TITLE
How to display XYPlot based on timeseries

### ISSUE THREAD

**Issue by forum6691** [PhilJay/MPAndroidChart#1036]
Hello everybody.
I wish to display a XYPLOT to display the speed of a vehicule.  Y data are the speed in km/h. Xdata are the time in millseconds and represents the hour/minute/seconds of the measure. The interval between X measures are variable because the acquistion system of the speed is not realtime. Example: the first measure is at 0 ms, the second at 10 ms, the third at 15 ms, the fourth at 23 ms, the fifth at 34 ms, and again...

So which graph can I use in MPandroidChart to display these type of measures ?
I read the wiki documentation thinking use the LineChart, but it seems that Xdata are just STRING and can not be a numeric value to have a variable scale along the Xaxis !

Thanks for help.

**Comment by Gary111** [comment]
I'll try to explain.

First of all you have to understand that **XData** is `List` of `String`s, because every `String` represents **XAxis label**, but not value. However index of `String` in `List` represents value. Lets say you have some data, for simplicity, we will take your data about the speed. Obviously, the grid interval for your data is one millisecond. If the total measurement time is *2 h : 15 m : 48 s : 432 ms*, that means that you have totally *8148432 ms*. And you have to generate **XData** approximately such way:

```java
List<String> xVals = new ArrayList<>();
for (int i = 0; i < 8148432; i++) {
    xVals.add(convertMsToHumanReadableTime(i));
}
```
But if every next measurements happens in time multiple of 5 ms (the first measure is at 0 ms, the second at 10 ms, the third at 15 ms, the fourth at 25 ms, the fifth at 35 ms, etc...), so you can assume grid interval is 5 ms. And next If the total measurement time the same: *8148432 ms*. And you have to generate **XData** approximately such way:

```java
List<String> xVals = new ArrayList<>();
for (int i = 0; i < 8148432; i += 5) {
    xVals.add(convertMsToHumanReadableTime(i));
}
```

Next you have to generate **YData**. `Entry` with `index` and `value` fields represents values you want to display on you chart. For you example:
> the first measure is at 0 ms, the second at 10 ms, the third at 15 ms, the fourth at 23 ms, the fifth at 34 ms
generation of **YData** should be something like this:

```java
List<SpeedMeasurement> speedMeasurements; // your real measurements
List<Entry> yVals = new ArrayList<>();
for (SpeedMeasurement speedMeasurement : speedMeasurements) {
    yVals.add(new Entry(speedMeasurement.getSpeed(), speedMeasurement.getTime()));
}
```

Thus, you generate the timeline and values for it based on your actual data. You can choose any type of chart, but I would advise you to a line chart. It's more actual for your data I think.

And the last one. A large number of data (e. g. 8148432) will greatly affect the performance of chart. I advise you to make an approximation and reduce the amount of data.

**Comment by forum6691** [comment]
Hi Gary111 and thank for this detailed explanation.
However, is your method or algoritm is useable if delta of time for between time measures is not fixed, like 1 ou 5 ms, but variable like 2 ms for the first delta, then 4 ms, then 5 ms, then 3 ms, then 7, and about...
I can't assume a fixed delta, because android system is not a determinist Operating system as you know.

**Comment by forum6691** [comment]
Ok, I solve my problem with your code Gary.
Now I have une other question.
How to reduce the number of data displayed ont the X axe ?
I looked at https://github.com/PhilJay/MPAndroidChart/wiki/Modifying-the-Viewport
but I don't find the right method. I tried setVisibleXRangeMinimum(20). It's ok and show 20 values max on the X axe, but I can't lower the zoom to show in manual more values !
I want initially show 20 values max at screen, but let the capability to the operator to show more value with a manual De-zoom.
Which is the right function for this ?
Thank you for your help.

**Comment by forum6691** [comment]
I have found a solution to display for example the 60 first value of my data series.
Here is the right code for this:

                long xvalCount=series.getXValCount();
		if(xvalCount>60) {
			PointF center=this.getCenterOfView();
			float scaleX=(float)xvalCount/60.f;
			zoom(scaleX, 1f,center.x,center.y);
		}

**Comment by forum6691** [comment]
Now I want to memorize the minX and maxX displayed, in order to redisplay the same viewport when I rotate my phone and my screen .

Is someone an idea ?

**Comment by Gary111** [comment]
Hi @forum6691 
you can use `LineChart.moveViewToX(int index)` to move your chart and use `LineChart.getLowestVisibleXIndex()` to get first visible index

**Comment by PhilJay** [comment]
also related to #12
