### ISSUE TITLE
Center description position

### ISSUE THREAD

**Issue by davix10** [PhilJay/MPAndroidChart#1053]
Hi, I would like to change the position of description. How do I centralize horizontally the description? I try to get pixels of screen and divide it by two but the description isn't perfectly in the center.
Thanks.

**Comment by PhilJay** [comment]
Thats because the description has text `Align.RIGHT`. So you need to calculate the width of the text too and divide that number by 2 and add that to your calculations to actually get the correct center position.

An alternative would be to use the `chart.getPaint(...)` method and set the text align to center.
