### ISSUE TITLE
Too small chart size

### ISSUE THREAD

**Issue by DonaldTC** [PhilJay/MPAndroidChart#1154]
I followed the steps in this video (https://www.youtube.com/watch?v=a20EchSQgpw) using Android Studio. When I ran the app on emulator, the char shrinked to the upper left corner of the screen instead of covering it (you may see the figure below). I wonder if there is anything I need to set in the project or it is the problem of the layout.
The sdk I used was 23.
![fig1](https://cloud.githubusercontent.com/assets/15341998/10758039/adaa5b54-7ce9-11e5-9076-84d48d224b03.png)

**Comment by fajprieto** [comment]
I have same problem. What is the solution, Can you help me?

**Comment by DonaldTC** [comment]
I tried addView(mChart, 200, 700) in the java code. It worked but not flexible.
Later, I created the view of my chart in xml layout file, like this:
```xml
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    
    <com.github.mikephil.charting.charts.LineChart
        android:layout_width="match_parent"
        android:layout_height="150dp"
        android:id="@+id/chart"/>

</LinearLayout>
```
This worked for me.
Hope it helps.

**Comment by fajprieto** [comment]
I try with your code, but it fail.
I make 2 layout:
- Main is the principal menu
- Calculo is the aplication with a lot of fields and a complex schema.

At the end of Calculo I put your code, well when I call Calculo from my smartphone the aplication stop with error and the Android Monitor say

Caused by: java.lang.ClassCastException: com.github.mikephil.charting.charts.LineChart cannot be cast to android.widget.LinearLayout
                                                                                      at com.integrales.creaciones.tuto01.Calculo.onCreate(Calculo.java:37)
 ...

I tryin now with add another layout to display the chart but this error for me is another problem.

What do yo think?

**Comment by fajprieto** [comment]
Well with this code:

miGrafico= (LinearLayout) findViewById(R.id.Grafico);
mChart=new PieChart(this);
miGrafico.addView(mChart,500,400);

Work for me, but I neet.
1) Put a caption, This with textview is posible.
2) Move the legends
3) Effect 3d. Is this possible? How?

Thanks in advance

**Comment by DonaldTC** [comment]
Perhaps you can check the javadoc. I only tried some functions of its linechart. Sorry about this.
