### ISSUE TITLE
error after updating to 2.2.0

### ISSUE THREAD

**Issue by babonski** [PhilJay/MPAndroidChart#1429]
hi, previously i used the version 2.1.6  before i decided to update to 2.2.0

however after i synced the graddle and tried to run it, there is an error that i don't understand.
it says
![screen shot 2016-02-02 at 3 39 00 am](https://cloud.githubusercontent.com/assets/8475841/12730492/cf966f52-c95e-11e5-9839-a8c94f0ff303.png)

that came from this line
` LineData data = new LineData(xVals, dataSets);`

anyone help? thanks

**Comment by PhilJay** [comment]
The constructor of `LineData` changed from

`LineData(List<String> xVals, List<LineDataSet>)`

to

`LineData(List<String> xVals, List<ILineDataSet>)`

So you need to create an arralist of the interface, thats all.

````java
ArrayList<ILineDataSet> sets ...;

LineData data = new LineData(..., sets);
````

**Comment by staz1000** [comment]
Phil, can you explain why this was changed? Just for my interest. I've taken on a project which uses LineDataSets, should I change them all?

**Comment by PhilJay** [comment]
If you want to use the new version, you have to change them.

This was changed because I added the feature to feed data to the chart in a customizeable way instead of predefined by the datasets. This allows you to create custom datasets that handle data differently but can still be used in the charts.
