### ISSUE TITLE
Gradle support

### ISSUE THREAD

**Issue by ilfuriano** [PhilJay/MPAndroidChart#16]
Add gradle support, please.

**Comment by elnazem** [comment]
Some problem occurred due to gradle changes, please fix them by upgrading the Gradle distribution to 5.x. Go to gradle-wrapper.properties and update :
distributionUrl=https\://services.gradle.org/distributions/gradle-5.2.1-bin.zip

you can refer to this post on stackoverflow:
https://stackoverflow.com/a/54667409/4409623
