### ISSUE TITLE
Wiki grouping

### ISSUE THREAD

**Issue by tomasKa** [PhilJay/MPAndroidChart#1650]
Great library, but it would be amazing if wiki was grouped better like 1. 2. 3 . ... 
Alphabetical sorting by title is probably not optimal for those who are getting started.

**Comment by PhilJay** [comment]
Okay, how would you improve it?

Currently it's not alphabetically sorted, but just numbered 1,2,3...

**Comment by ITM15-HR** [comment]
Hi, first of all, really great lib!!!!

And I think what tomasKa meant is, that on the right side of the wiki (Pages) the articles are sorted alphabetically instead of by chapter.

I also got a little refused by that, because I have always to switch back to the main Wiki article to go through it step by step!

**Comment by tomasKa** [comment]
Yes, I totally agree with ITM15-HR. This library being quite extensive, It would be beneficial if one could follow  it step by step. On the main wiki page it is sorted properly but on the right sidebar it is alphabetical. One either needs to keep the main wiki page open and open topics in new tabs or always scroll through the right hand side guessing "what's next important to know".Of course it is still useable but  I think having it sorted in the same way on the right side as on main wiki would make documentation more consistent and faster to use.

**Comment by PhilJay** [comment]
Please have a look now, is [this](https://github.com/PhilJay/MPAndroidChart/wiki) what you meant?

**Comment by ITM15-HR** [comment]
That's great. Thanks.

Am 19. April 2016 00:31:00 MESZ, schrieb Philipp Jahoda <notifications@github.com>:

Please have a look now, is this<https://github.com/PhilJay/MPAndroidChart/wiki> what you meant?

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub<https://github.com/PhilJay/MPAndroidChart/issues/1650#issuecomment-211608053>

--
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

FH JOANNEUM Gesellschaft mbH
Rechtsform/Legal form: GmbH
Sitz: Graz
Firmenbuchgericht/Court of registry: Landesgericht für ZRS Graz
Firmenbuchnummer/Company registration: FN 125888 f
DVR: 0813559
UID-Nr.: ATU 42361001
http://www.fh-joanneum.at/impressum
