### ISSUE TITLE
Draw view on chart.

### ISSUE THREAD

**Issue by arpitjoshi08** [PhilJay/MPAndroidChart#1706]
Is there any way to draw marker or view on pie chart ? according to my need i want to add view on pie chart please elaborate..

**Comment by PhilJay** [comment]
`MarkerView` can be used with the `PieChart` just like with any other chart.

https://github.com/PhilJay/MPAndroidChart/wiki/MarkerView

**Comment by daveatwork123** [comment]
My Requirements are a bit more sophisticated I need to be able to add up to 6 more icons to the center hole in the pie chart. I have managed to do this by Overlaying a layout atop the piechart center hole.

i have since detected that the pie chart does not allow us to 

1.pick up events from the phone screen around the center of a piechart with the centerhole removed/unused
2. Invisible slices are still activating events in the center hole even when disabled using currentChart.setDrawSlicesUnderHole(false); in PieChart
3. There is no way of associating an event with the text in the center hole in the PieChart

Is there anay way we could resolve this issues?

regards
David

**Comment by nazgul87** [comment]
Hi @PhilJay , I'm trying to draw a custom view on PieChart. I tried with marker, and everything works great, but I need to draw outside the chart (I'm using setYValuePosition(PieDataSet.ValuePosition.OUTSIDE_SLICE) and need this as label background).

Is there any way to move the marker and put it behind the Y Value label?

**Comment by HadiSaleem231** [comment]
@PhilJay Is there any way to add icons,labels, Variables, into central circle(hole) of pie chart at desired position?
