### ISSUE TITLE
Inaccurate values with valueformatter

### ISSUE THREAD

**Issue by IPolarI** [PhilJay/MPAndroidChart#1717]
I notice the way you're formatting the values is with floats. But with money I will  start getting inaccuracies if I try to display anything beyond 99,999.99 due to Java float precision. Is this just something I have to deal with?

**Comment by PhilJay** [comment]
Unfortunately yes. I suggest to avoid decimals for numbers higher than 1.000.000 - there is a very important reason `float` is used within this library. The reason is that Android matrix multiplications and canvas drawing (which are both crucial for this library and frequently used) are optimized for float values.

**Comment by PhilJay** [comment]
If you want to draw double values in your formatter, you can always provide them to the formatter directly (instead of getting them from the method parameter) and then display them. In that way you can have the chart use float values but you can display doubles.
