### ISSUE TITLE
Showing MarkerView below value

### ISSUE THREAD

**Issue by nangsan** [PhilJay/MPAndroidChart#1798]
Hi,
First thank you for this wonderful project.
I'm a newbie coding in android, but your project literally saves me a lot.
Though here's the issue, I'm desperately  trying to show the MarkerView below value in LineChart.

While skimming through your code, there's a method named drawMarkers in Chart class
tries to add offset when trying to show marker, I think its preventing marker from being shown above chart but, it backfires while I try to show below the value.

Here's the snippet,

               _if (pos[1] - mMarkerView.getHeight() <= 0) {
                    float y = mMarkerView.getHeight() - pos[1];
                    mMarkerView.draw(canvas, pos[0], pos[1] + y);
                } else {
                    mMarkerView.draw(canvas, pos[0], pos[1]);
                }_

**Comment by TeunKooijman** [comment]
When extending the MarkerView class, you are forced to implement two methods called `getXOffset(float xpos)` and `getYOffset(float ypos)`. You can use these methods to tell the chart where to draw the marker views upon highlighting.

To show the marker above the value you can use:

```
    @Override
    public int getYOffset(float ypos)
    {   return getHeight() * - 1;}
```

To show the marker view below the value, I suppose you could simply change this to return the positive value of getHeight(), so that:

```
   @Override
    public int getYOffset(float ypos)
    {   return getHeight();}
```

Hope this helps.

**Source:** [MarkerView Wiki](https://github.com/PhilJay/MPAndroidChart/wiki/MarkerView)
