### ISSUE TITLE
Scatter points are cropped in Combined chart

### ISSUE THREAD

**Issue by EduardDenisjonoks** [PhilJay/MPAndroidChart#1817]
I have issue described here:
http://stackoverflow.com/questions/37462636/mpandroidchart-scatter-points-are-cropped-in-combined-chart

Any way to solve it or work around?

**Comment by PhilJay** [comment]
This will be fixed in the next release.

**Comment by akshaytaru2007** [comment]
@PhilJay @EduardDenisjonoks  any solution to this? I am facing same issue.

**Comment by EduardDenisjonoks** [comment]
@akshaytaru2007  https://stackoverflow.com/questions/37462636/mpandroidchart-scatter-points-are-cropped-in-combined-chart you can see here some work arounds

**Comment by akshaytaru2007** [comment]
I saw that link. But problem is one of my scatter point has `y = 0`. and If I use your solution then (0,0) gets shift little bit upwards and it does not look good. This problem is with the Combine chart. 
If you use only line chart and if one of your point is on x axis because y is 0 then the points comes on x - axis but it does not get cropped.

**Comment by EduardDenisjonoks** [comment]
Hmm, in that case I would say if Phil didn't fix this you could try to use multiple chart views overplayed maybe
