### ISSUE TITLE
Bar height not proportional to it's value

### ISSUE THREAD

**Issue by KnightYusuf** [PhilJay/MPAndroidChart#1845]
when i have two bars one with value 3 and the other with value 1; normally the height of the first bar is three time the height of the second
but it's not the case in this chart:
![bar_bug](https://cloud.githubusercontent.com/assets/1111431/15832096/2e41b228-2c10-11e6-84f8-1d97fdfa57c1.png)

could you please help me!

**Comment by bogdanzurac** [comment]
I can confirm this behavior.

Neither are the values of each bar proportional to the total sum of values of the chart (in your case, the first bar with value 3 proportionate to total value 18, so the first bar should be 1/6 of the total height), nor are they proportionate related to each other, with the highest value being the tallest one (in your case 4th bar with value 1 should be 1/3rd of the height of the first bar, since the first one is the highest value, like you mentioned).

So something is definitely wrong. I presume the 2nd case I mentioned should be the intended behavior, right?

**Comment by KnightYusuf** [comment]
Yes the 2nd case is the intended behavior.

**Comment by PhilJay** [comment]
There are two possible issues:

 - your axis does not start at 0, which would cause the "lower" part of all bars to be cut off, in that case, set `yAxis.setAxisMinValue(0f)`
 - your formatter is cofigured to display only integer values and hence, a number like 1.9 is drawn with a height representing 1.9 but shown as "1"

**Comment by bogdanzurac** [comment]
Setting the min value on the Y axis to 0 solved it. I assumed this was the default value. Thanks for clearing that out.

Is there a reason why you're setting the Y min value to the min value of all the bars - the bottom space?
