### ISSUE TITLE
"Configuration with name 'default' not found"

### ISSUE THREAD

**Issue by tonypatino-monoclesociety** [PhilJay/MPAndroidChart#1921]
Introduced in branch remove_xindeces in commit a233e3 https://github.com/PhilJay/MPAndroidChart/commit/a233e389783ed2ec308bd4d0af372617981b0e2e

I can no longer clean or rebuild the project.  When attempting either, I receive this error on Gradle sync : "Configuration with name 'default' not found"

In Gradle Build, the output is 
Error:A problem occurred configuring project ':MPChartExample'.
> Cannot evaluate module MPChartLib-Realm : Configuration with name 'default' not found.

**Comment by tonypatino-monoclesociety** [comment]
I'll wait until this is resolved before making a pull request with the performance updates, since part of my changes involved the now-deleted Realm java classes.

**Comment by PhilJay** [comment]
I have moved the realm related code to a separate repository due to their recent changes related to the realm dependency inclusion (now via gradle plugin). 

https://github.com/PhilJay/MPAndroidChart-Realm

I have some work left to do on the remove_xindices branch and on the new realm repository which will take a couple of more days (maybe a week). As soon as this is finished I will publish a v3.0.0 pre release. Maybe it is best to wait for the performance updates until that release is out, and then make a PR there. I will then include the PR into the final v3.0.0 release.

**Comment by tonypatino-monoclesociety** [comment]
Sounds good.  v3.0.0 post-release might be less of a moving target as well, and I'll have some time to check for more allocation hotspots in the meantime.
