### ISSUE TITLE
3.0.0-beta1 - Linechart rendering glitches

### ISSUE THREAD

**Issue by TeunKooijman** [PhilJay/MPAndroidChart#2001]
Since upgrading to the v3.0.0-beta1 version of the library, my dynamic (realtime) charts seem to experience weird rendering glitches. These glitches do not occur under certain circumstances (so they occur at random), nor do they occur every time. Please refer to the following video to see what I mean. My apologies for the video being as long as it is, it took a while for the glitch to occur this time. It occurs from 1.25 to 1:48.

https://lookback.io/watch/C3wmQGCSvd5mkdHbK

Do you have any idea what might be causing this?

**Comment by PhilJay** [comment]
Thanks for the video, it's always good to have something other than textual description.

Are you absolutely certain that this did not occur in older versions of the library?

**Comment by TeunKooijman** [comment]
I a fairly certain about this yes. It started to occur as soon as I implemented the newly added support for x index values (in this case amount of milliseconds since the start of the session).

**Comment by daedamr** [comment]
This is happening for me also, and i am also updating the values in real time (about 1 per second). Tried it with also 5 seconds and the same thing happens, so it cannot be concurrency change problem. I have never seen it before updating. You can see it in the attached video by TeunKooijman at 1:44. Parts of the charted data flicker somehow. And always at the beginning of the chart.

I am adding values like in dynamic example:

```
                                lineDataSet.addEntry(new Entry(newEntryX, readingValue));
                                lineDataSet.notifyDataSetChanged();
                                mainLineChart.notifyDataSetChanged();
                                mainLineChart.moveViewToX(newEntryX);
```

Tried also with only _invalidate_ instead of _moveViewToX_ and same thing happens.

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
