### ISSUE TITLE
CombinedChart with only BarData showing improperly

### ISSUE THREAD

**Issue by sickmartian** [PhilJay/MPAndroidChart#2017]
Hi, first of all great library, thanks a lot!

Sorry if I'm missing something obvious, I'm having a strange behaviour with a CombinedChart, I was able to replicate it with the example for CombinedChart (CombinedChartActivity.java) if you just leave the BarData it's shown improperly.

Having this:
    //      data.setData(generateLineData());
            data.setData(generateBarData());
    //      data.setData(generateBubbleData());
    //      data.setData(generateScatterData());
    //      data.setData(generateCandleData());
Shows:
<img width="426" alt="screen shot 2016-07-13 at 10 22 18 pm" src="https://cloud.githubusercontent.com/assets/492246/16825130/4cc18778-4948-11e6-9601-7a69ef761ff2.png">

But with any other type of data added, like so:
    //      data.setData(generateLineData());
            data.setData(generateBarData());
    //      data.setData(generateBubbleData());
    //      data.setData(generateScatterData());
            data.setData(generateCandleData());
It's shown properly:
<img width="454" alt="screen shot 2016-07-13 at 10 23 14 pm" src="https://cloud.githubusercontent.com/assets/492246/16825142/808ce4d0-4948-11e6-81f3-74282360772e.png">

Important bit I forgot, I'm on the latest version, I understand that this wasn't supported until recently.

**Comment by PhilJay** [comment]
This is because the way the chart treats the x-axis has changed in v3.0. Now, the developer has full control over what is displayed. All you need to do here is set a different range for the x-axis, or a different bar width.

`xAxis.setAxisMaximum(...)`
`xAxis.setAxisMinimum(...)`

`barData.setBarWidth(...)`

Example:

If your x-axis range is 10 and you place one bar at x-position 8 (bar center), and the bar has a width of 4, it will display on the right side of the chart, with the right bar edge aligning with the right "end" of the drawing area. The left side of the bar will be at x-psition 6.
