### ISSUE TITLE
Not find setSpaceBetweenLabels's LineChart method

### ISSUE THREAD

**Issue by foxsent** [PhilJay/MPAndroidChart#2114]
Not find setSpaceBetweenLabels's LineChart method

**Comment by PhilJay** [comment]
Due to recent changes in v3.0.0, this method is no longer available (and needed). The `XAxis` values are now treated similar to `YAxis` values.

Spacing between axis labels can be controlled via the `setLabelCount(...)` method of the axis or via custom [formatters](https://github.com/PhilJay/MPAndroidChart/wiki/The-AxisValueFormatter-interface).
