### ISSUE TITLE
Question: How to update from 2.2.5 to 3.0.0 when using custom subclasses

### ISSUE THREAD

**Issue by tthtrifork** [PhilJay/MPAndroidChart#2372]
First of all thanks for a great library!

I've been using it for a while now, and would like to update to v3.0.0 from v2.2.5.

But I can see there are a lot of breaking changes and new ways to do things.
Would it be possible to make a migration guide to help the process?

All the best!

**Comment by PhilJay** [comment]
Currently there is no plan for a migration guide, since this would be very time consuming. The most breaking changes are mentioned here: https://github.com/PhilJay/MPAndroidChart/releases

Other than that, I suggest you rely on the examples and ofc source code of the new version to help your migration.
