### ISSUE TITLE
barDataSet.setBarSpacePercent is not found

### ISSUE THREAD

**Issue by yswheye** [PhilJay/MPAndroidChart#2524]
I want  to set BarChart bar space width 0, how can i do?

**Comment by onebee** [comment]
you can use barDataSet.setBarWidth(0.1f);

**Comment by newcici7777** [comment]
barDataSet.setBarSpacePercent is not found
barDataSet.setBarWidth(0.1f); is not found

I use BarData.setBarWidth(0.1f);
It doesn't work!

**Comment by almic** [comment]
Hey there! This issue is fairly old, and may no longer apply to the current library version. I'm closing this in order to clean up the issue tracker. The repository has been inactive for a long time and old issues may have existing answers or are no longer valid.

I've been working diligently to get to as many issues as I can, but I can no longer spend time writing a unique answer to each issue. This is especially true if that issue may no longer be applicable. If you think this was done by mistake, please search through all `open` and `closed` issues first, and then create a new one using the templates.

This is a copied and pasted response, and has been put on many other issues. So please, don't take this personally.
