### ISSUE TITLE
Support set step value for Horizontal and Vertical Axis (x/y axis)

### ISSUE THREAD

**Issue by tsengvn** [PhilJay/MPAndroidChart#269]
Hi, after deeply searching in this lib, I see you do not support for setting these values yet. 

For example, I have a bunch of data of temperature of few months, and I want to draw a chart with step in Y axis is 5 degree, and step in X axis is each 7 days, what I want is the gridline always point to that step value. 

I see some others chart lib have this feature, but I love this library (the style, animation, setup). Could you please add this in next release ?

Thanks.

**Comment by zhoujiancs** [comment]
Also have the same problem. 

The YAxis calculates itself automaticly, but sometimes we just want to define it by code. 

As @PhilJay mentioned on StackOverflow(http://stackoverflow.com/questions/28753540/force-barchart-y-axis-labels-to-be-integers), "The mEntries array that holds all the axis labels is public." But when I tried to modify mEntries, it doesn't work, because the chart will re-calculate the y axis values in onDraw().

Need help. I need suggestions about how to do this.

**Comment by PhilJay** [comment]
On the x-axis, you can now set that via calling:

`setLabelsToSkip(int count)`

**Comment by tsengvn** [comment]
thanks Phil, but how about the YAxis ?
