### ISSUE TITLE
Horizontal bar Chart  can achieve this effect?

### ISSUE THREAD

**Issue by maoai-xianyu** [PhilJay/MPAndroidChart#2723]
Horizontal bar Chart  can achieve this effect? I have this problem. Can you help me.
![image](https://cloud.githubusercontent.com/assets/17868022/22005689/4e84ec08-dca0-11e6-8329-62f9488091e5.png)
I need your help. Thanks

**Comment by xiaolongonly** [comment]
什么问题？我想我可以帮助你~

**Comment by maoaixianyu** [comment]
中文，可以呀。用作者的Horizontal bar Chart  , 如何将100 写在条形图上。
作者是
![qq20170117-0](https://cloud.githubusercontent.com/assets/17868022/22012070/4fa93274-dccd-11e6-814d-da9687162f1b.png)
我的如我提问的图形，将作者的图片的我圈红的数字的位置换到我的位置上（条形图上的100），谢谢

**Comment by xiaolongonly** [comment]
嗯，想修改这里的话你可能要修改框架的代码。我可以帮你改一下 应该不难。只要
![image](https://cloud.githubusercontent.com/assets/12853050/22048861/bc40a7c6-dd6a-11e6-8fbd-c6f9dcc1b861.png)绘制的位置减去文字加小空格的长度

**Comment by xiaolongonly** [comment]
嗯，目前官方的api没有这样的方法，但我想你可以通过修改源代码来实现。 我这边也帮你做了一下测试。。
首先你要找到 HorizontalBarChartRenderer 这个类。
找到里面的绘制的代码。
  drawValue(c, formattedValue, buffer.buffer[j + 2] + (val >= 0 ? posOffset : negOffset),
                                y + halfTextHeight, dataSet.getValueTextColor(j / 2));
修改为
    drawValue(c, formattedValue, buffer.buffer[j + 2] - (val >= 0 ? posOffset : negOffset) - Utils.calcTextWidth(mRenderPaint, formattedValue),
                                y + halfTextHeight, dataSet.getValueTextColor(j / 2));
![qq 20170118111339](https://cloud.githubusercontent.com/assets/12853050/22049584/2eaac1e4-dd6f-11e6-853e-30aebe7e8552.png)

希望我的回答能帮助到你

**Comment by maoaixianyu** [comment]
ok，谢谢。已经用上了。忘记回复了。thanks

**Comment by fanyuzhing** [comment]
你好，ghost。

如果左侧的月份放到蓝色调上面靠左，可以实现吗？
我设置XAixs position 为 BOTTOM_INSIDE ，但是不起作用。

该怎么修改呢？谢谢。

**Comment by blankfu** [comment]
@ghost 你好，可以帮我一下吗，我现在遇到了horizontalchartbar  左边的label显示不完整的问题，左边有部分文字绘制到了屏幕外

**Comment by almic** [comment]
Sorry to ruin the party, but this issue tracker tries to maintain a primarily english language. I will try to help despite this, but in such a case where an entire discussion is going on in chinese is not very helpful for the maintainers of this library.

I am working on an update that adds improved label positioning for bar charts. Can't remember if I pushed it yet, but it is coming in the next version. I'm closing this since the issue will be resolved soon, and I know there are other issues asking the same thing in english.
