### ISSUE TITLE
LineChart circle fill color

### ISSUE THREAD

**Issue by lahiruchandima** [PhilJay/MPAndroidChart#288]
How can I change the fill color of a point circle? I tried LineDataSet.setCircleColor() but it only changes the circle outline color. Fill color is always white.

![screenshot_2015-01-05-13-57-12](https://cloud.githubusercontent.com/assets/5843590/5610789/f2fa972c-94e2-11e4-9311-8a8af2478244.png)

Thanks in advance

**Comment by PhilJay** [comment]
That is not directly possible.

However, you can access the `Paint` object that is used for drawing the inner circles and do whatever you want with it:

```java
Paint circlePaint = chart.getPaint(Chart.PAINT_CIRCLES_INNER);
circlePaint.setColor(...);
```

**Comment by Maragues** [comment]
@PhilJay I guess that's no longer possible on v2.0.7, since there's no such *Chart.PAINT_CIRCLES_INNER* constant.

From what I see, you need to access *mCirclePaintInner* in *LineChartRenderer*, but that can only be done by using your own *LineChartRenderer*. That's why I've created https://github.com/PhilJay/MPAndroidChart/pull/429
