### ISSUE TITLE
BarChart Axis setAxisLineDashedLine method does not work

### ISSUE THREAD

**Issue by subhan-nadeem** [PhilJay/MPAndroidChart#3026]
For example, if I wish to call the following code:

`mChart.getAxisLeft().setAxisLineDashedLine(new DashPathEffect(new float[]{10f, 5f}, 0));`

I do not get a dash path effect on my chart (see attached file for image of resulting chart).

In my AndroidManifest.xml I have set ` android:hardwareAccelerated="false"`, as specified by documentation

![applicationframehost_2017-04-18_14-54-14](https://cloud.githubusercontent.com/assets/17396392/25180010/49578a56-24da-11e7-841a-3d26e568db3a.png)

**Comment by zhenqinrui** [comment]
I also got the question? do you solve?

**Comment by almic** [comment]
Hey there! This issue is fairly old, and may no longer apply to the current library version. I'm closing this in order to clean up the issue tracker. The repository has been inactive for a long time and old issues may have existing answers or are no longer valid.

This issue, however, appears to be asking for help. This issue tracker is not for [support questions](https://github.com/PhilJay/MPAndroidChart/edit/master/.github/ISSUE_TEMPLATE/Support_help.md) or personal debugging. If you have questions, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mpandroidchart) and ask your questions there. You could also read the [documentation](https://github.com/PhilJay/MPAndroidChart/wiki/) and look at the [example app](https://github.com/PhilJay/MPAndroidChart/tree/master/MPChartExample), it probably has what you're looking for.

This is a copied and pasted response, and has been put on many other issues. So please, don't take this personally.
