### ISSUE TITLE
请问如何对直方图 饼图颜色设置为渐变

### ISSUE THREAD

**Issue by siliconvallley** [PhilJay/MPAndroidChart#3354]
请问如何对图表颜色设置为渐变

**Comment by gb18030** [comment]
https://github.com/PhilJay/MPAndroidChart/pull/3317
应该打上这个patch就能渐变了 我没试 但是看说明的意思应该是渐变

**Comment by siliconvallley** [comment]
请问什么patch 能说下具体方法吗

**Comment by siliconvallley** [comment]
咋个取修改源码  实现渐变的效果

**Comment by siliconvallley** [comment]
我尝试了修改 但是这是修改折线图的方式 参考了下 用在直方图好像不是太实用

**Comment by harcoPro** [comment]
а по русски нельзя?

**Comment by xAqweRx** [comment]
@harcoPro видать не могут :) 
@siliconvallley  I could probably help if you'll tell what do you want in english

**Comment by siliconvallley** [comment]
@xAqweRx I want to the BarChart, PieChart color is set to gradient  , I don't know this patch (https://github.com/PhilJay/MPAndroidChart/pull/3317) is right or not

**Comment by xAqweRx** [comment]
Currently was implemented only for line chart, but I can look on bar chart and pie chart

**Comment by siliconvallley** [comment]
you hava the source code for the PieChart and BarChart color is set to gradient

**Comment by siliconvallley** [comment]
@xAqweRx

**Comment by xAqweRx** [comment]
@siliconvallley  do you need something like this? 
![screenshot_20170910-075729](https://user-images.githubusercontent.com/9740874/30096589-870ecc70-92d9-11e7-8d45-d2b6d6584e3e.png)

**Comment by xAqweRx** [comment]
Please specify what kind of gradient do you wont. I will try to implement it in my branch. May be that after some time this feature will be present in main stream

**Comment by siliconvallley** [comment]
@xAqweRx  yes! should be hele me, but you can provide this code for me!

**Comment by EmMper** [comment]
@xAqweRx 
Hello, I have the same issue with @siliconvallley ,but I wonder if BarChart or any other Chart could set the background (maybe it is not called "background", but I think you know what I mean) so that we could change the bar (or other shapes in other chart forms) color or drawable whatever we want. 
I see the code and could not find any function which could do this, so here is my suggestion:Will you please let the color or the drawable of the chart shape (just like the bar in barchart) could be set.
My English is not well, I hope you could get me.
Thanks.

**Comment by xAqweRx** [comment]
@EmMper  I think that I've understood you. But changes that I've made are not changing "shape" of chart. And currently - there is not possibility to do this. I'll think about this. And will try to add support of drawable for chart.

**Comment by EmMper** [comment]
@xAqweRx OK, thanks.

**Comment by almic** [comment]
sorry but this issue tracker is strictly english only. We cannot help you with this.

Closing old issue. If anyone still has this question please open a new one. (in english)
