### ISSUE TITLE
 PieChart sets multiple colors, but sometimes only one color is displayed

### ISSUE THREAD

**Issue by CQBOBOZHU** [PhilJay/MPAndroidChart#3520]
like this 

normal 
![image](https://user-images.githubusercontent.com/20177774/31992326-9c547982-b9ac-11e7-9432-c98f7ffb0b5b.png)

error

![image](https://user-images.githubusercontent.com/20177774/31992356-afc925a8-b9ac-11e7-886c-61e7bd7a0b9f.png)

how to do

**Comment by CQBOBOZHU** [comment]
Occasionally this happens

**Comment by DiegoVenancioVieira** [comment]
Which is the solution for this?

**Comment by DiegoVenancioVieira** [comment]
Solution is add:

        // add a lot of colors

        ArrayList<Integer> colors = new ArrayList<Integer>();

        for (int c : ColorTemplate.VORDIPLOM_COLORS)
            colors.add(c);

        for (int c : ColorTemplate.JOYFUL_COLORS)
            colors.add(c);

        for (int c : ColorTemplate.COLORFUL_COLORS)
            colors.add(c);

        for (int c : ColorTemplate.LIBERTY_COLORS)
            colors.add(c);

        for (int c : ColorTemplate.PASTEL_COLORS)
            colors.add(c);

        colors.add(ColorTemplate.getHoloBlue());

        dataSet.setColors(colors);

**Comment by xkludge** [comment]
I had the same issue, the problem was there same color slices had a abs value of 1.

**Comment by almic** [comment]
Hey there! This issue is fairly old, and may no longer apply to the current library version. I'm closing this in order to clean up the issue tracker. The repository has been inactive for a long time and old issues may have existing answers or are no longer valid.

I've been working diligently to get to as many issues as I can, but I can no longer spend time writing a unique answer to each issue. This is especially true if that issue may no longer be applicable. If you think this was done by mistake, please search through all `open` and `closed` issues first, and then create a new one using the templates.

This is a copied and pasted response, and has been put on many other issues. So please, don't take this personally.
