### ISSUE TITLE
Bug？AxisLeft still affects AxisRight if make AxisLeft.setEnabled(false)

### ISSUE THREAD

**Issue by EDMKG** [PhilJay/MPAndroidChart#375]
Hi, Mr PhilJay, thanks for your great job..

when my codes like below:
mChart.getAxisRight().setEnabled(true);
mChart.getAxisLeft().setEnabled(false);
mChart.getAxisRight().setStartAtZero(false);

the view of candlestickchart will be shown unnormal, there will be a big blank under the candlestick line,
so i have to add codes:
mChart.getAxisLeft().setStartAtZero(false);
to solve this problem,  and i thoungt that we don't need to add the codes after setting left axis disable..

Just a feedback
Best regards,
ED_MKG

**Comment by PhilJay** [comment]
Thanks for pointing that out, I will have a look at it!

**Comment by PhilJay** [comment]
Figured it out :-)
It's not a bug, however its probably not quite clear yet because the new code is not yet documented.

If you are using only the right axis, make sure you set the `AxisDependency` for your `DataSet` correctly. The `AxisDependency` specifies the axis (LEFT or RIGHT) the data should be plotted against, and by default, this is set to LEFT.

So if you only have a right axis, do this:

```java
CandleDataSet set = new CandleDataSet(...);
set.setAxisDependency(AxisDependency.RIGHT);
```

.. and it should work.

**Comment by EDMKG** [comment]
Thank u very much
