### ISSUE TITLE
Bar entry Problem

### ISSUE THREAD

**Issue by eduxcellence** [PhilJay/MPAndroidChart#3801]
1f 2 f 3 f 4 f..and so on i want to change in integer value

**Comment by almic** [comment]
Hey there! This issue is fairly old, and may no longer apply to the current library version. I'm closing this in order to clean up the issue tracker. The repository has been inactive for a long time and old issues may have existing answers or are no longer valid.

This issue, however, appears to be asking for help. This issue tracker is not for [support questions](https://github.com/PhilJay/MPAndroidChart/edit/master/.github/ISSUE_TEMPLATE/Support_help.md) or personal debugging. If you have questions, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mpandroidchart) and ask your questions there. You could also read the [documentation](https://github.com/PhilJay/MPAndroidChart/wiki/) and look at the [example app](https://github.com/PhilJay/MPAndroidChart/tree/master/MPChartExample), it probably has what you're looking for.

This is a copied and pasted response, and has been put on many other issues. So please, don't take this personally.
