### ISSUE TITLE
Is there a way to add space in between the outer slice and inner circle?

### ISSUE THREAD

**Issue by AlexDang** [PhilJay/MPAndroidChart#3802]
Is it possible add space/padding in between the outer slice and inner circle?  My inner circle has background color of red.  The slices are green, blue, etc...  How do I create some space in between my inner red circle to the colored slices?  The only way I can think of is to add a white circle object on top of the piechart with the right radius, but is there anyway to achieve this easier with mpandroidchart's api call?

Thanks.

**Comment by MGaetan89** [comment]
Have you tried with:
https://github.com/PhilJay/MPAndroidChart/blob/6fbd49276168b6270a85cc8ddb2d655b0afaa1f2/MPChartLib/src/main/java/com/github/mikephil/charting/data/PieDataSet.java#L59-L73

**Comment by almic** [comment]
Hey there! This issue is fairly old, and may no longer apply to the current library version. I'm closing this in order to clean up the issue tracker. The repository has been inactive for a long time and old issues may have existing answers or are no longer valid.

I've been working diligently to get to as many issues as I can, but I can no longer spend time writing a unique answer to each issue. This is especially true if that issue may no longer be applicable. If you think this was done by mistake, please search through all `open` and `closed` issues first, and then create a new one using the templates.

This is a copied and pasted response, and has been put on many other issues. So please, don't take this personally.

-----

This is kind of a feature request, from what I gather you want empty space between the inner circle and the outer chart. I recommend you search existing issues to see if this is a duplicate. If you can't find anything, open a new one with the proper feature request template and I'll add it to the project board.
