### ISSUE TITLE
Not able to set scrollbar indicator in cubic line chart  

### ISSUE THREAD

**Issue by mahanteshrobo** [PhilJay/MPAndroidChart#3812]
I have drawn a cubic line chart with horizontal scroll. But not able to set scroll bar indicator for horizontal scroll. Below is the code which i tried 

   mChart.setScrollBarStyle(SCROLLBARS_OUTSIDE_OVERLAY);
   mChart.setScrollBarSize(100);
   **mChart.setHorizontalScrollBarEnabled(true);**

**Comment by almic** [comment]
Hey there! This issue is fairly old, and may no longer apply to the current library version. I'm closing this in order to clean up the issue tracker. The repository has been inactive for a long time and old issues may have existing answers or are no longer valid.

This issue, however, appears to be asking for help. This issue tracker is not for [support questions](https://github.com/PhilJay/MPAndroidChart/edit/master/.github/ISSUE_TEMPLATE/Support_help.md) or personal debugging. If you have questions, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mpandroidchart) and ask your questions there. You could also read the [documentation](https://github.com/PhilJay/MPAndroidChart/wiki/) and look at the [example app](https://github.com/PhilJay/MPAndroidChart/tree/master/MPChartExample), it probably has what you're looking for.
