### ISSUE TITLE
StackedBarChart - set colour by index?

### ISSUE THREAD

**Issue by gfdarcy** [PhilJay/MPAndroidChart#3814]
Is it possible to set the color of a StackBarChart entry based on its index in the array?
This means all of the 1st items are red (for example), and all of the 2nd items are blue. 
Keep in mind some values might be 0.

**Comment by almic** [comment]
Hey there! This issue is fairly old, and may no longer apply to the current library version. I'm closing this in order to clean up the issue tracker. The repository has been inactive for a long time and old issues may have existing answers or are no longer valid.

I've been working diligently to get to as many issues as I can, but I can no longer spend time writing a unique answer to each issue. This is especially true if that issue may no longer be applicable. If you think this was done by mistake, please search through all `open` and `closed` issues first, and then create a new one using the templates.

This is a copied and pasted response, and has been put on many other issues. So please, don't take this personally.
