### ISSUE TITLE
BarChart with Horizontal Scroll

### ISSUE THREAD

**Issue by ZakiResoluteSolutions** [PhilJay/MPAndroidChart#3815]
I am not able to scroll the Bar Chart Horizontally. Please suggest me what can i do?

My BarChart xml code:

`<com.github.mikephil.charting.charts.BarChart
            android:id="@+id/chart_graph"
            android:layout_width="wrap_content"
            android:layout_height="300dp"
            android:layout_gravity="center"
            android:layout_marginBottom="10dp"
            android:layout_marginLeft="15dp"
            android:layout_marginRight="15dp"
            android:layout_marginTop="10dp">`

I am using "mpandroidchartlibrary-2-1-6.jar". In the latest version of your library you update BarChart for Horizontal scrolling?

**Comment by almic** [comment]
Hey there! This issue is fairly old, and may no longer apply to the current library version. I'm closing this in order to clean up the issue tracker. The repository has been inactive for a long time and old issues may have existing answers or are no longer valid.

I've been working diligently to get to as many issues as I can, but I can no longer spend time writing a unique answer to each issue. This is especially true if that issue may no longer be applicable. If you think this was done by mistake, please search through all `open` and `closed` issues first, and then create a new one using the templates.

This is a copied and pasted response, and has been put on many other issues. So please, don't take this personally.
