### ISSUE TITLE
Can't use exponents in chart

### ISSUE THREAD

**Issue by praveenbroski** [PhilJay/MPAndroidChart#3816]
Cannot use exponents in linechart

My `LineChartDataSet` is 
[Charts.LineChartDataSet, label: H2S, 8 entries:
ChartDataEntry, x: 0.0, y -4.17182640083098e-31
ChartDataEntry, x: 1.0, y -1.1803449813502e-30
ChartDataEntry, x: 2.0, y -2.1877250545198e-30
ChartDataEntry, x: 3.0, y -9.75872621107585e-31
ChartDataEntry, x: 4.0, y -3.30704526095548e-30
ChartDataEntry, x: 5.0, y -8.66391654939365e-31
ChartDataEntry, x: 6.0, y -3.21778307409011e-30
ChartDataEntry, x: 7.0, y -4.95139615350815e-30]

When I tries to set this to linechart the app stucks forever.

Can we use very small decimal values like above in linchart?
Is there any workaround for this?

Thanks.

**Comment by almic** [comment]
Hey there! This issue is fairly old, and may no longer apply to the current library version. I'm closing this in order to clean up the issue tracker. The repository has been inactive for a long time and old issues may have existing answers or are no longer valid.

I've been working diligently to get to as many issues as I can, but I can no longer spend time writing a unique answer to each issue. This is especially true if that issue may no longer be applicable. If you think this was done by mistake, please search through all `open` and `closed` issues first, and then create a new one using the templates.

This is a copied and pasted response, and has been put on many other issues. So please, don't take this personally.
