### ISSUE TITLE
when setInverted(true) in the leftAxis of CombinedChart, the candleStickData doesnot show ?

### ISSUE THREAD

**Issue by JusticeOfHeaven** [PhilJay/MPAndroidChart#3822]
![20180228142522](https://user-images.githubusercontent.com/23259769/36773920-ebef015e-1c96-11e8-8f13-95f19abe5765.png)

where was wrong ? Help ！

**Comment by almic** [comment]
Hey there! This issue is fairly old, and may no longer apply to the current library version. I'm closing this in order to clean up the issue tracker. The repository has been inactive for a long time and old issues may have existing answers or are no longer valid.

I've been working diligently to get to as many issues as I can, but I can no longer spend time writing a unique answer to each issue. This is especially true if that issue may no longer be applicable. If you think this was done by mistake, please search through all `open` and `closed` issues first, and then create a new one using the templates.

This is a copied and pasted response, and has been put on many other issues. So please, don't take this personally.
