### ISSUE TITLE
Different Shadow layer for 2 different lines

### ISSUE THREAD

**Issue by nicatguliyev** [PhilJay/MPAndroidChart#3839]
I am using MPchart lib in android. I have 2 line in graphView. And i want to add 2 different color shadow layer for each line. But i can add same color For each line. To add shadow layer i am using These codes: mChart.setLayerType(View.LAYER_TYPE_SOFTWARE, null); mChart.getRenderer().getPaintRender().setShadowLayer(3, 5, 3, Color.GRAY);
 How to make different shadow colors?

**Comment by almic** [comment]
Marking as a `wontfix` due to how small of a detail this is. If this library added every small detail requested it would bloat the library significantly with so many design options that finding the ones you want would be very difficult, and would make the useful ones hard to find underneath all the insignificant options.

Since we cannot add all small design requests, we cannot add *any* small design requests. The only requests accepted are significant and obviously beneficial. This request is simply too small and insignificant to be worth adding, even if it makes the chart look fancier, it does not add any significant benefit.
