### ISSUE TITLE
Toast/ ToolTip/ MarkrView for Stacked Bar Chart / Horizontal Bar Chart.

### ISSUE THREAD

**Issue by akkishinde** [PhilJay/MPAndroidChart#386]
Hi Phil..!

Can you add Y index Entry so one can get Tool tip for Stacked Bar Chart & Horizontal Bar Chart. 
Do you have any workaround for this functionality.!?

**Comment by PhilJay** [comment]
Since the latest commit, each stacked value of a bar-entry can be highlighted separately: https://github.com/PhilJay/MPAndroidChart/commit/02e8149f5d40cdabc4692f1dbac93ed9d20309f7

Example here: https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/StackedBarActivity.java

**Comment by akkishinde** [comment]
Thank you Phil, But still the specific segment of Stack is not highlighting. If you touch to the stack the stack index values are correct but only highlighted are should be the specific stack & not the whole bar from the touched stack.
