### ISSUE TITLE
YAxis Labels gets exptra, unnecessary padding on YAxis formatter change

### ISSUE THREAD

**Issue by przemek-baranowski** [PhilJay/MPAndroidChart#3866]
When I'm adding new set with different data type (%) I'm updating right axis formatter to different one. After that I'm updating LineData and calling invalidate() on chart.
Seems pretty standard case, but the effect is like below:
[https://s3-eu-west-1.amazonaws.com/uploads-eu.hipchat.com/157498/3183982/4bvTKP8iwHO29ap/didd.png](screenshot)

Bottom one is one after update. Can spot the right spacing difference? it's pretty annoying and breaks UX :(

**Comment by almic** [comment]
First of all, dead image link. Github lets you attach images directly, use that instead because that way you know people will be able to see the image.

Also, without actual code, there is no way to tell what is actually causing this problem, whatever that problem actually is (no image).

If you are still having this issue, please **open a new issue** and attach your images and some sample code (DO NOT paste the entire file, only the necessary code).
