### ISSUE TITLE
Is it possible to hide the pie chart when click the button or line chart 

### ISSUE THREAD

**Issue by github9604** [PhilJay/MPAndroidChart#3875]
I wonder whether it is possible to hide and show pie chart depend on which part of line chart user clicks!

**Comment by almic** [comment]
If you are asking to remove specific slices of the pie chart, you should be able to do that by just changing the colors to include a transparent color for the one you want to hide.

Otherwise, this issue doesn't explain enough for me to understand exactly what you are asking. Since this issue is so old, I'm going to close it with the assumption you've already figured this out or no longer need it.

If you are still having this problem, please **open a new issue** and describe what you want in more detail.
