### ISSUE TITLE
Line Chart : Value switch form zero not correct

### ISSUE THREAD

**Issue by vidsag** [PhilJay/MPAndroidChart#3928]
I was playing around with the line charts and noticed this.

![test](https://user-images.githubusercontent.com/18425326/38482039-4ad0e728-3beb-11e8-943a-2a5e6ee9c3de.png)

I was streaming y value as 0 for some time and then a constant 68. Here you can see the first value change form 0 to 68 is not correct. How can i overcome this?

**Comment by almic** [comment]
I guess you're talking about that *spike* just before it goes to 68. This is fixed by using the `dataSet.setMode()` to something like `LineDataSet.Mode.HORIZONTAL_BEZIER` or `LineDataSet.Mode.LINEAR`

Right now it looks like you're in `LineDataSet.Mode.CUBIC_BEZIER` mode, which tries drawing a much curvier line between points.

I'd recommend playing with the `cubicIntensity` with `dataSet.setCubicIntensity()`, if you want to keep the cubic mode.
