### ISSUE TITLE
legend.getColors() deprecated. How to get legend colors

### ISSUE THREAD

**Issue by afinas-em** [PhilJay/MPAndroidChart#3934]
I want the legend colors as an array. But now it shows that the code is deprecated. Please help me

**Comment by almic** [comment]
The legend colors are IDENTICAL to the data set colors in your graph. If you have changed the colors of the legend, then you should already know the colors you set them to, as well as have access to the original data sets whose colors you've also set, although changing the legend colors *afterwards* is a little redundant since you should've set them in the datasets before hand.

[xkcd](https://xkcd.com/530/)
