### ISSUE TITLE
How to set the legend values side by side

### ISSUE THREAD

**Issue by KKeerthini** [PhilJay/MPAndroidChart#3945]
I have 4 legend values so I am trying to display first to legend values as a set
and the next 2 legend below it.Is it possible

**Comment by almic** [comment]
Check this code excerpt from the LegendEntry class:

```java
/**
     *
     * @param label The legend entry text. A `null` label will start a group.
     * @param form The form to draw for this entry.
     * @param formSize Set to NaN to use the legend's default.
     * @param formLineWidth Set to NaN to use the legend's default.
     * @param formLineDashEffect Set to nil to use the legend's default.
     * @param formColor The color for drawing the form.
     */
    public LegendEntry(String label,
                       Legend.LegendForm form,
                       float formSize,
                       float formLineWidth,
                       DashPathEffect formLineDashEffect,
                       int formColor)
    {
        this.label = label;
        this.form = form;
        this.formSize = formSize;
        this.formLineWidth = formLineWidth;
        this.formLineDashEffect = formLineDashEffect;
        this.formColor = formColor;
    }
```

In the `@param` definitions, it says this about the `String label`:
> The legend entry text. A `null` label will start a group

You may not be able to group them in a 2x2 square, but you should be able to clearly separate them vertically by using a `null` label in between. You could also set the `form` to `LegendForm.LINE` to draw a horizontal line (I think).

I haven't tested this myself, but that's a good place to start. I'm closing this because, although you can't set them as a 2x2 square, it is probably best to put them on different lines as it makes it more obvious which colors go to which labels.

**Comment by KKeerthini** [comment]
Thank you...I'll check on that
