### ISSUE TITLE
Line chart with spesific Zoom

### ISSUE THREAD

**Issue by arifinreinaldo** [PhilJay/MPAndroidChart#3957]
Hi, I've been using your library for the past two month.s

I wonder if it Is  possible line chart shows spesific part of data?

for example I have 20 data, I have to zoom precisely at 15th to 20th data only but I can still drag and zoom to other previous data

Thank you

**Comment by almic** [comment]
You can easily change the "zoom" by changing the visible range.
`chart.setVisibleXRange(min, max)`
`chart.setVisibleYRange(min, max)`

You can also animate this by doing `zoomAndCenterAnimated()` on the chart.

**Comment by arifinreinaldo** [comment]
Thanks almic, it works

**Comment by almic** [comment]
Thanks for the update, glad it worked

**Comment by almic** [comment]
@helloworld10010 I am not really helping people anymore on this project, I'm sure you are looking for a logarithmic sort of view, however. It is not good practice to comment on an issue asking a different question, and I would normally recommend that you make a new issue. But, please, do not open an issue for this sort of trivial question. I strongly encourage you to find a better way to display your data through trial and error rather than asking here.

**Comment by helloworld10010** [comment]
> @helloworld10010 I am not really helping people anymore on this project, I'm sure you are looking for a logarithmic sort of view, however. It is not good practice to comment on an issue asking a different question, and I would normally recommend that you make a new issue. But, please, do not open an issue for this sort of trivial question. I strongly encourage you to find a better way to display your data through trial and error rather than asking here.

It is precisely because it is trivial that I have not opened a new issue. already solved, although it took a day
