### ISSUE TITLE
CombinedChart crashes randomly : Attempt to read from null array in BarChartRenderer

### ISSUE THREAD

**Issue by ArilesGit** [PhilJay/MPAndroidChart#3959]
Hello and thank you for all your work creating this library,
@PhilJay, can you tell me if this is a bug or is there something I'm doing wrong.

I'm having a really hard time finding the source of this **random** crash.
Thank you very much for your help.

Here is a [link to the stackOverflow](https://stackoverflow.com/questions/49905089/mpandroidchart-combinedchart-crashes-randomly-barchartrenderer) question I created. I provided a sample code and the full stacktrace.

**Comment by RobertZagorski** [comment]
Please check once again, if calling `chart.notifyDataSetChanged();` right after `chart.setData(combinedData);` fixes the issue or not.

**Comment by ArilesGit** [comment]
Hi @RobertZagorski, I will try your suggestion and get back to you. It may take some time though, because the crash doesn't happen too often.

That being said, why do I need to do this ? The data does not change after `chart.setData(combinedData)`.

**Comment by ArilesGit** [comment]
Hi !
I just wanted to tell that I don't have any news yet, but I keep watching.
At the moment my app runs on 3 devices only. I may release it to more people soon.
I'll keep you posted.

**Comment by ArilesGit** [comment]
Hello !
We still haven't release the app to more people, but we've had 1 crash so far. Even with  @RobertZagorski's suggestion, so it still happens.

**Comment by almic** [comment]
This should be fixed now in d67ea481af1e8528c617dfd404d0c7827b0134b2. I am not going to release v3.1.0 for a while though, so you'll need to clone the entire project for now to get this fix.

**Comment by ArilesGit** [comment]
Thank you for your work @almic, I'll try to check this out soon. :+1:

**Comment by estrnod** [comment]
Hi - I know this is a belated response, but I still, with v3.1.0, have a similar (I think the same) issue with a BarChart and "Attempt to read from null array" in BarChartRenderer.  It is actually not random; I have tested it until it was reproducible by trying to refresh my chart while the animation was still going.  If I wait until the animation finishes, it always works.  If I try to refresh it while the animation is active, the exception occurs.  I was unable to correct it by checking for null data passed in to the chart (as far as I can tell) but I was able to work around it by using "synchronized" on the methods that would trigger an update to the chart, so that it could not be updated until it was finished (apparently; I can click the switch on the emulator screen to rapidly refresh it while it is animating and now it always resolves eventually without getting an exception.)
