### ISSUE TITLE
How do I compute the grid lines manually?

### ISSUE THREAD

**Issue by cekoivisto** [PhilJay/MPAndroidChart#3965]
I have a candlestick chart and I'm trying to put the date of the entry on the x-axis. I understand how to use the axis value formatter, but the problem is the location of the grid lines don't line up on the dates that I want. For example if I have a candlestick chart that shows data over multiple years, when the user zooms out I want the grid lines to snap to the very first candle of each year as opposed to them being drawn wherever they are calculated. And if the user zooms in more, the grid lines would snap to the first candle in each month, etc. I understand that there is no way for the library to know where these candles are by itself, so which functions would I have to override to make this possible?
Thanks

**Comment by almic** [comment]
You can manually change the number of labels, which is how the gridlines are drawn. Just call `xAxis.setLabelCount(count, true)` to force it to draw what you want to be shown. You can also adjust the granularity of the chart so that your labels are drawn on the months or the years, by changing it from 1 to 12. Check out the [javadoc](https://jitpack.io/com/github/PhilJay/MPAndroidChart/v3.0.3/javadoc/), and go to the AxisBase class to see the functions you have at your disposal.

Keep in mind, the library has a hard limit of 2-25 for the number of labels drawn.

**Comment by FrancoSabadini** [comment]
Hi, I'm having a similar issue, but I want to show the grid at irregular places, e.g., see the pic below.

<img width="287" alt="screen shot 2018-05-17 at 12 29 30 pm" src="https://user-images.githubusercontent.com/5099645/40150508-18c43004-59ce-11e8-9928-c7d7b54d993c.png">

How can I do this? I've been searching through the Javadocs and online but can't find a way.

**Comment by almic** [comment]
@FrancoSabadini please DO NOT post on closed issues asking questions. This issue tracker is not for support questions. If you have questions, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mpandroidchart) and ask your questions there. You could also read the [documentation](https://github.com/PhilJay/MPAndroidChart/wiki/) and look at the [example app](https://github.com/PhilJay/MPAndroidChart/tree/master/MPChartExample), it probably has what you're looking for.
