### ISSUE TITLE
Question: Is it possible to update the text shown above the markers in line chart?

### ISSUE THREAD

**Issue by SeppPenner** [PhilJay/MPAndroidChart#3988]
Is it possible to add e.g. the a custom text and the y value to the text that is shown above the marker circles in a line chart?

The https://github.com/PhilJay/MPAndroidChart/wiki/MarkerView seems to be deprecated in the latest version of the library?

![grafik](https://user-images.githubusercontent.com/9639361/39406358-ee2dde24-4bb5-11e8-984f-0d8d88ca7672.png)

Is there another way to do this in the current library release?

**Comment by almic** [comment]
Looks like the method you want in this case is `Chart.getMarker()`, not `Chart.getMarkerView()`.

That's probably happened because someone decided to simplify the name to just `Marker` in some places, but but forgot to unify the name everywhere. It should be called `MarkerView` everywhere, in my opinion, since the base class is also called MarkerView. May be "undeprecated" soon if I have anything to do about it, but I'll investigate why this decision was made.

For now, check out the example LineChartActivity1.java in the example project, it uses a custom marker "view" called `MyMarkerView`. It looks like you're trying to get an instance of the MarkerView, however you'll need to create one yourself, there is no default MarkerView.

**Comment by SeppPenner** [comment]
Hi again @almic,

I finally managed what I wanted to do using your suggestion. The example provided is much better than the documentation wiki (Sorry for bashing you here again 😺 )

I used now the implementations from https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/LineChartActivity1.java:

```java
MyMarkerView mv = new MyMarkerView(this, R.layout.custom_marker_view);
mv.setChartView(mChart); // For bounds control
mChart.setMarker(mv); // Set the marker to the chart
```

The Markerview from here: https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/custom/MyMarkerView.java (with adaptations of course) and the XML layout from here: https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/res/layout/custom_marker_view.xml

The last passage is just included if anyone has the same issue.
