### ISSUE TITLE
Rounding issue with Entry for LineChart

### ISSUE THREAD

**Issue by ronakp** [PhilJay/MPAndroidChart#4026]
I am using LineChart for my application. I have my dataset and I am converting it to Entry object.

`entry.add(new Entry(chartsData.getX, chartsData.getY.floatValue()));`

My original data class has x value of 1494460800000 and y value of 0.6789696642998889
but my entry object has x value of 1.49446079E12 and y value of 0.6789697.

Is there any way to persist original non-rounded values in entry object? 
also,
 Is there any way of using Big decimal or double values in entry object?

**Comment by RobertZagorski** [comment]
> Is there any way of using Big decimal or double values in entry object?

No. Whole library is done around `float` type of Entries
>Is there any way to persist original non-rounded values in entry object?

Override a chart and method: [Chart#setupDefaultFormatter(float min, float max)](https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartLib/src/main/java/com/github/mikephil/charting/charts/Chart.java#L375) supplying your own IValueFormatter implementation

**Comment by almic** [comment]
Charts are *not* designed to use such large numbers, and neither are end-users. Cut those numbers down to size! MPAndroidChart has these great features like the `ValueFormatter` and `AxisValueFormatter` which allow you to convert big numbers into more meaningful information for your users. Instead of using `526186449`, cut it down and format it into `526M`! Try to not blindly pump big numbers into your charts, as they are intended to help people visualize a lot of data in a simple format.
