### ISSUE TITLE
Can I achieve the current depth map?

### ISSUE THREAD

**Issue by dalingge** [PhilJay/MPAndroidChart#4028]
Such as Binance！

**Comment by almic** [comment]
You cannot say "like [insert name here]" and expect someone to go researching what that is to understand what you mean when you say that. I can tell English isn't your language, because I have no clue as to what "achieve the current depth map" actually means.

This issue tracker is not for [support questions](https://github.com/PhilJay/MPAndroidChart/edit/master/.github/ISSUE_TEMPLATE/Support_help.md) or personal debugging. If you have questions, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mpandroidchart) and ask your questions there. You could also read the [documentation](https://github.com/PhilJay/MPAndroidChart/wiki/) and look at the [example app](https://github.com/PhilJay/MPAndroidChart/tree/master/MPChartExample), it probably has what you're looking for.
