### ISSUE TITLE
如果改变barchart使柱状顶部为圆角矩形

### ISSUE THREAD

**Issue by zhenqinrui** [PhilJay/MPAndroidChart#4039]
是否是修改BarChartRenderer的drawDataSet方法，里面有个绘制drawRect改为drawRoundRect，有已经新增该解决的吗？不然就得自己去重写下

**Comment by almic** [comment]
Marking as a `wontfix` due to how small of a detail this is. If this library added every small detail requested it would bloat the library significantly with so many design options that finding the ones you want would be very difficult, and would make the useful ones hard to find underneath all the insignificant options.

Since we cannot add all small design requests, we cannot add *any* small design requests. The only requests accepted are significant and obviously beneficial. This request is simply too small and insignificant to be worth adding, even if it makes the chart look fancier, it does not add any significant benefit.

---
**footnote**: Please refrain from using a language other than English on this issue tracker. The maintainers aren't language geeks and have to use Google Translate just to get an idea of what you're saying, and it isn't perfect.

**Comment by LXLYHM** [comment]
圆形柱状图，重写要怎么重写？

**Comment by LXLYHM** [comment]
> 是否是修改BarChartRenderer的drawDataSet方法，里面有个绘制drawRect改为drawRoundRect，有已经新增该解决的吗？不然就得自己去重写下

你好，最后怎么解决的？
