### ISSUE TITLE
Combined Bar Chart X-Axis Labels not centered aligned.

### ISSUE THREAD

**Issue by pankaj210891** [PhilJay/MPAndroidChart#4045]
I am showing two data series in a combined bar chart, but the labels on the x-axis are not getting center aligned. I tried to find solution many times but no success even on StackOverflow, I posted a question on [SO](https://stackoverflow.com/questions/49442357/dynamic-labels-not-center-aligning-to-bar) but didn't get any solution. Currently, I am getting results as below, some labels are placed at the center of bar and some at the end of bar whereas I want all to be aligned in the center.

You can check the result image [here.](https://ibb.co/bESZYy)

Below is the code:

```
BarDataSet set = new BarDataSet(entries, "");
        set.setColors(getResources().getColor(R.color.observed_bar));
        set.setValueTextSize(6f);
        set.setDrawValues(true);

        BarDataSet setCompare = new BarDataSet(entriesCompare, "");
        setCompare.setColors(getResources().getColor(R.color.random_bar));
        setCompare.setValueTextSize(6f);
        setCompare.setDrawValues(true);

        ArrayList<IBarDataSet> dataSets = new ArrayList<>();
        dataSets.add(set);
        dataSets.add(setCompare);

        float groupSpace = 0.10f;
        float barSpace = 0.02f; // x2 dataset
        float barWidth = 0.40f; // x2 dataset

        BarData data = new BarData(dataSets);
        data.setBarWidth(barWidth);
        data.setValueFormatter(new PercentFormatter());

        chart.setDrawBarShadow(false);
        chart.setDrawValueAboveBar(false);
        chart.setData(data);
        chart.setDrawGridBackground(false);
        chart.setFitBars(true);
        chart.setDrawValueAboveBar(true);
        chart.invalidate();
        chart.setTouchEnabled(false);
        chart.setDragEnabled(false);
        chart.setDrawBorders(false);
        chart.getDescription().setEnabled(false);
        chart.getLegend().setEnabled(false);   // Hide the legend
        chart.getXAxis().setAxisMinimum(0);
        chart.getXAxis().setAxisMaximum(0 + chart.getBarData().getGroupWidth(groupSpace, barSpace) * groupCount);
        chart.groupBars(0, groupSpace, barSpace); // perform the "explicit" grouping

        chart.getAxisLeft().setDrawAxisLine(false);
        chart.getAxisRight().setDrawAxisLine(false);
        chart.getXAxis().setDrawGridLines(false);

        YAxis leftAxis = chart.getAxisLeft();
        leftAxis.setEnabled(false);
        YAxis rightAxis = chart.getAxisRight();
        rightAxis.setEnabled(false);
        Legend legend = chart.getLegend();
        legend.setEnabled(false);

        XAxis xAxis = chart.getXAxis();
        xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
//        xAxis.setLabelCount(groupCount - 1);
        xAxis.setLabelCount(xLabel.size() - 1);
        xAxis.setTextSize(6f);
        xAxis.setDrawAxisLine(false);
        xAxis.setDrawGridLines(false);
        xAxis.setCenterAxisLabels(true);
        xAxis.setLabelRotationAngle(60f);
        xAxis.setValueFormatter(new IndexAxisValueFormatter(labels));
```
Thanks.

**Comment by RobertZagorski** [comment]
`setCenterAxisLabels` on XAxis is known to have issues.
Putting another issues for reference:
#3810
#3908

**Comment by almic** [comment]
Both this issue and the SO question have quite different examples, so I'll try to answer them both in a meaningful way.

**This issue**: Did you forget about `setGranularity()`?

**SO Question**:
Rotating labels isn't perfect when it comes to angles outside 90 degree turns. It would require some trivial maths to solve, but I somewhat question the design choice for using tilted labels instead of fully horizontal or vertical labels. Using tilted over vertical is good for when the label is too long for both orientations, but using a tilted label over a horizontal one is pointless for labels which easily fit horizontally, and it only makes it harder to read.

It also raises the question that you may be choosing labels which are so long that they can't fit horizontally, and are also too long to be easily read when vertical. I think label rotation should be limited to either horizontal or vertical rotations only. As a UI designer, you need to question if such long labels are helpful to the user, and try to think of a creative way to shorten them without losing information.

For example, I have a chart that shows populations in various countries. For each axis label, I could put the full country name, but some are so long that it becomes difficult to read. Take this very real country name, "Democratic Republic of the Congo." Instead of using the full name, I can safely shorten it to something like "Congo, D-R" without losing it's meaning. Obviously there may be shorter official names, but this is just a quick example.

----
Closing issue, if you don't think my suggestions solve your problem, feel free to keep commenting on this post with more information. I will read your comments, promise :)
