### ISSUE TITLE
I need the X axis label to be 2 lines

### ISSUE THREAD

**Issue by pikaboo** [PhilJay/MPAndroidChart#4283]
Currently i have

![image](https://user-images.githubusercontent.com/3405551/47962936-be425080-e02c-11e8-9474-791499d7f6e8.png)

And I need to achieve
![image](https://user-images.githubusercontent.com/3405551/47962942-d023f380-e02c-11e8-9441-b81d4130f059.png)

How do I style the axis label this way ?

If possible, please reply as soon as possible, I only have 1 week to fix this

**Comment by almic** [comment]
I'm fairly certain this **is not** supported at the moment, and may not be for a long time. If you have to accomplish something like this, I can only suggest to add text views beneath the chart and try to line them up as best you can. Please look through the examples and the wiki to see if anything can remedy this, but I'm pretty sure there isn't multi-line support for labels. You'll honestly need to show the labels in another way as multiple lines are probably out of the question right now.

**Comment by pikaboo** [comment]
This method is written in your code
![image](https://user-images.githubusercontent.com/3405551/48029271-7e778800-e156-11e8-9057-583c2cddb567.png)

its name suggests "multiline label text"
it is just never invoked anywhere

Is there a way for me to invoke it ?

**Comment by almic** [comment]
I'm not sure if you know this, but this library was *sort of* abandoned for a very long time, hence over 4000 issues, 20% of which are all about the same problems, 50% are basic usage questions, and the rest are design questions that I'm slowly whittling down. Also there are many issues over 3 years old.

This code was added over 3 years ago by this commit: 3074744db7bb1fccbaac17f4737742c5e27ad465

And it seems like nothing happened after that, so that code is just sitting there doing nothing. Multiple line support is something I would like to add, but right now I need to solve the documentation problem that causes so many simple questions to be opened all the time, as well as patching a few bugs and adding redundancy to the library to reduce the number of user errors.

If you'd like to create a pull request that adds this functionality, I will gladly review it some time in the future. But for now you just have to find your own solution that works until someone gets around to adding this.
