### ISSUE TITLE
Charts duplicating android 9

### ISSUE THREAD

**Issue by lababiba** [PhilJay/MPAndroidChart#4302]
<img width="540" alt="llpp" src="https://user-images.githubusercontent.com/14142618/48360810-add34b00-e6a8-11e8-95db-57be8908f0de.png">
<img width="360" alt="pie" src="https://user-images.githubusercontent.com/14142618/48360811-add34b00-e6a8-11e8-94b0-9d2deb3871d0.png">

Its the same app with the same chart, running android 5.0 and android 9. As you see, in android 9 charts line duplicating. Its happen only on android 9 (tested 5.0 - 8.1).

Code of chart initialiation https://gist.github.com/lababiba/cb6977154c732ca1d92b5579cbe71269

**Comment by almic** [comment]
Unless you provide some code no one will be able to help you. Please create a gist and link it here.

**Comment by lababiba** [comment]
> Unless you provide some code no one will be able to help you. Please create a gist and link it here.

https://gist.github.com/lababiba/cb6977154c732ca1d92b5579cbe71269

**Comment by almic** [comment]
So the only thing I can think of is that your entries may be getting added twice. Since you only provided the chart initialization it's obvious that it's not due to a double y-axis. If you have any code that is run depending on the version of the device, especially when you create the data (which you only showed the setup for the data set) then that could be causing this.
Basically, from what you provided, the only thing left is that your data is being changed inside an API version check somewhere outside that code. Since I can't recreate this I'm going to close the issue.
