### ISSUE TITLE
show big value (double value) in pie chart

### ISSUE THREAD

**Issue by hamidchi** [PhilJay/MPAndroidChart#4311]
I'm using a pie chart in my activity. When I set a big value into the entries, it doesn't show the value correctly.

For example:

My value is 627050000 but the chart shows is 627049986,

or

my value is 477470000 but the chart shows is 477470016.
.
I read about ValueFormatter class also using BigDecimal but I didn't understand. Please help and explain in a simple way.

Thanks.
.
my question at stackoverflow 
https://stackoverflow.com/questions/53353002/show-big-numbers-double-value-in-pie-chart-using-mpandroidchart

**Comment by almic** [comment]
@hamidchi I believe I already responded to you in another issue, but I'll do it here just in case.

I personally wouldn't recommend using such large values in charts, even if you require precision. Instead, you should put the exact number somewhere else, as a chart is designed to show the data simply at a glance.

Despite that, I would still like to add support for larger values anyway. But I can't give you a timeline of when that might be added. For now, use the chart to show the data at a glance; don't worry about high precision. Place the precise data elsewhere in your layout. That way users can glance at the chart and then determine if they really need the exact data by scrolling down or tapping the chart.

Remember that you don't have to use the data passed to the value formatter! You can easily initialize it with a reference to an object you use to store the precise data, before converting it to a float for the chart. You get the index, and then just reference the precise object instead of the value held in the entry.
