### ISSUE TITLE
LineChart - SingleValue without setStartAtZero is not visible

### ISSUE THREAD

**Issue by MFlisar** [PhilJay/MPAndroidChart#503]
Drawing a line chart with a single value does not show this value. Only if the value is not 0 AND setStartAtZero is enabled, the chart does show the value...

**Comment by PhilJay** [comment]
Circles enabled?

**Comment by MichaelFlisar** [comment]
yes. and show labels as well.

I experience the same behaviour if I have multiple values and all are 0 only...

**Comment by MichaelFlisar** [comment]
Here's a screenshot. It uses the same graph, just with different data.

In the first graph you see the values. The second graph has 3 0 values at exact the same position as the first one... But you can't recognise them because they are not drawn... Probably it has to do something with the y axis bounds?

![a](https://cloud.githubusercontent.com/assets/2437726/6963750/eb3ce6d0-d942-11e4-8335-b0e1e955c269.png)

**Comment by PhilJay** [comment]
I think this a known issue not yet fixed in v2.0.8.
But it should already be fixed in the latest commit that is not yet in a release version.

So you could check out that commit or wait thill v2.0.9 is released, which will be soon.

**Comment by MichaelFlisar** [comment]
Thanks a lot, I will wait and check that
