### ISSUE TITLE
The smooth curve not accurate using mDrawCubic = true 

### ISSUE THREAD

**Issue by kapiluiet** [PhilJay/MPAndroidChart#51]
A  big issue I am facing is that I need the line chart to be smooth, hence I changed your library code: protected boolean mDrawCubic = true; in LineChart.java.
  Now the chart looks smooth but has some incorrect positions. You can see the popup coming above the graph in http://i60.tinypic.com/2mpig3r.jpg also in this you can see some of the Y axis values above or below the curve, http://i62.tinypic.com/21mcbw5.png . How can I resolve this Phil ?

**Comment by abouda** [comment]
I see that this issue is still present in the latest version (1.7.4). It seems that it deliberately draws the extra curve after the point, which makes it look like the point value is wrong when you hide the circles:
![screenshot_2015-02-19-13-57-13](https://cloud.githubusercontent.com/assets/4817549/6266986/37361850-b840-11e4-912b-3f3f1974880d.png)

In fact it seems like the curve limit is the point, which it isn't.
![screenshot_2015-02-19-14-05-45](https://cloud.githubusercontent.com/assets/4817549/6267064/1d942a3a-b841-11e4-8306-8f157a361c30.png)
