### ISSUE TITLE
need clarification on my error message

### ISSUE THREAD

**Issue by nbau21** [PhilJay/MPAndroidChart#538]
I'm trying to make multiple charts show up in a listview (just like in the sample). However, I keep getting this weird error. All my other charts work, but getting to my LineChart crashes my listview. 

ClassCastException: com.nbau21.zledger.Charts.HorizontalBarChartItem$ViewHolder cannot be cast to com.nbau21.zledger.Charts.LineChartItem$ViewHolder

Here is what LineChartItem.java looks like:

    @Override
    public View getView(int position, View convertView, Context c) {
        //put chart into view
        ViewHolder holder;

        if (convertView == null) {

            holder = new ViewHolder();

            convertView = LayoutInflater.from(c).inflate(
                    R.layout.list_item_linechart, null);
            holder.chart = (LineChart) convertView.findViewById(R.id.lineChart);

            convertView.setTag(holder);

        } else {
                holder = (ViewHolder) convertView.getTag();   <--- the line throwing the error
        }
    }
       private static class ViewHolder {
            LineChart chart;
    }

Any clue as to what is causing this error would help a lot! Thanks.

**Comment by PhilJay** [comment]
This issue is not related to the library.

This is an issue in the implementation of your multi-layout (items of different classes) `ListView` that causes a ClassCastException when the listview recycles its childs.

Take a look at the example project and see how I implemented a multi-layout listview.
Especially on these methods in the adapter:

```java
       @Override
        public int getItemViewType(int position) { ... }
        
        @Override
        public int getViewTypeCount() { ... }
```

Tutorial: http://www.survivingwithandroid.com/2014/08/android-listview-with-multiple-row.html

**Comment by nbau21** [comment]
Thanks, your advice helped. Sorry for the confusion!
