### ISSUE TITLE
BarChart, set different colors for bars based on Y-Value

### ISSUE THREAD

**Issue by sarathnagesh** [PhilJay/MPAndroidChart#593]
Thank you, awesome library. 

I think the title explains clearly What I'm looking for. I want different colors for the bars in a vertical bar chart depending upon on the values in the Y-axis, Like if Y-Value > 100, Color = Red.

![6vzi8](https://cloud.githubusercontent.com/assets/12132062/7342893/051ad9d8-ecd8-11e4-89e7-28057aac48f6.png)

Is it possible to achieve this?

**Comment by danielgindi** [comment]
Not currently, but it would involve adding an interface for fetch the color for a bar based on it's value. Not too complicated.

**Comment by SilverFoxA** [comment]
Have you considered trying to add the colors on your own instead of using the color template i think its easy to achieve what you want through the implementation of code, trying setting color based filed in dataset and check for the value, use a a condition which checks which color to use and done... hope it gives you a fair idea

**Comment by PhilJay** [comment]
#517
