### ISSUE TITLE
Add manual entries to legend? 

### ISSUE THREAD

**Issue by dowi** [PhilJay/MPAndroidChart#596]
i have only one LineData but with some colors to the circles of the points
and i want the legend to contain those colors 

i tried using
getLegend().setColors(legendColors);
getLegend().setLabels(legendLabels);
but it didnt work

and i couldnt find a way to create a legend and set it

how can i achieve that?

thanks!

**Comment by dbleicher** [comment]
@dowi - I don't have a fix to offer, but perhaps an observation might help.  I was experiencing this same issue when using Daniel Gindi's Swift port (ios-charts) of MPAndroidChart.  I created my chart inside of a cell within a UICollectionView, and created the custom legend with the methods you note above.  When I first run the app, the legend shows entries from the dataset, appearing to ignore my calls to setColors and setLabels.  However, if I scroll the cell off screen, and then scroll it back onto the screen (causing the CollectionView to redraw the cell), my custom legend appears perfectly.  

So, at least for me, setColors and setLabels are working, but the chart is not being redrawn after these values are set.  You may want to look into forcing a redraw or relayout (invalidate()?) of your chart after setting your custom legend values.  Also, I believe that setting chart data populates the legend, so I think you'll need to set the custom values AFTER setting the chart's data.  Hope that helps.

**Comment by dowi** [comment]
Hi and thanks a lot!

i tried what you suggested and you are right! 

only problem is even with invalidate i first see the wrong legend, and only after it is drawn and the invalidated it is right. 
still didnt figure out how to set it right from the get go.. will keep trying

**Comment by dbleicher** [comment]
@dowi  - I've looked through the code as best I can, and either I'm misunderstanding the chart's "lifecycle" (order in which key events occur), or I need to make a Feature Request for enhancement to that lifecycle.  Perhaps @PhilJay can shed some light if he gets a chance.  Here's what I think happens:

1. Chart's view is initialized
2. User code can create datasets and combine into a ChartData object
3. If the user sets the Chart's data, the chart is rendered (setting data triggers the render)
4. If the user doesn't set the Chart's data before returning control, rendering is still triggered but with a "No chart data available" message being the only rendered output.
5. If the user has set data, and later changes that data, notifyDatasetChanged() will cause the underlying data to be recalculated (overwriting custom legend info?) and re-rendered.

Our first problem is with step 3.  Ideally, there would be a way to set the data, but NOT render the chart (or at least, defer the render).  I can think of two reasons why this would be desirable:  animation (#585) and custom legends (#596).  If we could fully configure the entire chart (data, legend, etc.) before triggering the render, then we could animate the initial chart display (instead of showing the result and then invalidating/animating, would eliminate the "flash") and our custom legend would be correct on first viewing.

Step 5 represents a lesser issue, and only for the custom legend.  I believe that notifyDatasetChanged() will regenerate legend data overwriting any custom colors/labels that have been set.  It would be helpful to be able to call notifyDatasetChanged(), and then reapply custom legend information, before the re-render.

If I'm right about the lifecycle, it might be possible to accommodate the change without breaking existing code.  Perhaps we could add an an override of setData(ChartData data) that accepts a flag to defer rendering like setData(ChartData data, Boolean renderNow), and then add a method on the Chart that just renders (without reevaluating data)?  Just a thought.

**Comment by PhilJay** [comment]
@dbleicher you have more or less understood the problem correctly. However, upon e.g. setting up a `View` inside lets say the `onCreate(...)` method of an `Activity`, it automatically gets rendered, I cannot change that.

And rendering causes the data (as you said correctly), to recalculate all values (also the legend), and this is why your custom set legend entries are overwritten by the recalculation.

Of course this could be solved via some kind of boolean flag like "ifcustomlegendset then dont recalculate" but this is in my opinion a very ugly workaround.

If someone could find a nice and clean solution for this or show me a way of preventing the view from being rendered upon setting it up, I would very much appreicate it :-)

**Comment by dbleicher** [comment]
Thanks @PhilJay, and thank you for this excellent library!  I'll look through the code some more and see if I can figure out something to contribute.

**Comment by dowi** [comment]
hi and thanks to both of you!

maybe you can add the ability to set multiple legends (one below the other) so that the first one is the automatic one and allow to show/hide each individually

this is also good for scenarios where you have multiple sets representing somethings and colors representing something else.

thanks a lot

**Comment by danielgindi** [comment]
Maybe we should just add the "custom" boolean flag, as people may want to manually calculate their legends anyway...

**Comment by danielgindi** [comment]
https://github.com/PhilJay/MPAndroidChart/pull/657

**Comment by PhilJay** [comment]
Now possible.

**Comment by dowi** [comment]
thanks a lot it works great!
