### ISSUE TITLE
The complete Label is not getting displayed in Horizontal view

### ISSUE THREAD

**Issue by SilverFoxA** [PhilJay/MPAndroidChart#615]
I was using the bar chart and in the following i have the labels as the month names, i do get the bars but the labels are missing it's not displaying the consecutive lables, where i think it should display the complete lable or else it should be scrolable horizontally
![graph](https://cloud.githubusercontent.com/assets/6983070/7441031/864916b4-f0f2-11e4-93e2-fbe6219a995d.png)

**Comment by dbleicher** [comment]
@SilverFoxA  - The chart is automatically skipping every other month label to ensure that it can display the full label text for each.  If your chart was wider, you would see all the labels.  There are a couple of ways to fix this, however, and the chart DOES support scrolling.  To have the scrolling and all labels, use:

    myBarChart.setDragEnabled(true); // on by default
    myBarChart.setVisibleXRange( 3 ); // sets the viewport to show 3 bars

Instead of the "3", choose whatever value is small enough so that all the month labels appear.  When you run this, the chart can be scrolled to show the additional xValues by touch dragging.

**Comment by SilverFoxA** [comment]
Sorry sir, but the above mentioned code is not working for me. I have tired 
`barChart.setVisibleXrange(1); ` but i don't see any changes where as it should show me only 1 bar if i'm not wrong and depending on the entries the bar width decreases to fit the layout hence dragging is also not working for me

**Comment by dbleicher** [comment]
@SilverFoxA - Hmmm... works fine for me.  One thing you may need to do is set this AFTER setting the chart's data.  Can you give that try?  If that doesn't work, can you post your code?

**Comment by SilverFoxA** [comment]
ohhhh i got the answer actually i was setting the fields before setting the data.... Sir, can you please let me know how can i change the left legend text with the currency symbol, it will be very helpful

**Comment by dbleicher** [comment]
@SilverFoxA - glad you got it working.  As for formatting the values, I think you're referring to the yAxis values (rather than a separate legend).  You'll use a ValueFormatter for this as explained in the docs:  https://github.com/PhilJay/MPAndroidChart/wiki/The-ValueFormatter-interface

**Comment by SilverFoxA** [comment]
Thank you sir it really helped i think i should read the complete wiki first :D

**Comment by Deaful** [comment]
> you must setVisibleXRange() AFTER setting the chart's data

Thank you very much, it works.
