### ISSUE TITLE
Programmatically deselect value on piechart

### ISSUE THREAD

**Issue by Manhazito** [PhilJay/MPAndroidChart#745]
Hi!
If I click a value on a piechart it gets selected, and when I then call highlightValues(...) or highlightTouch(...) with a null argument, it looks deselected. But the next click on the graphic is ignored. It's as if the value is not highlighted but is still selected. Is there a way to really deselect a value (just like a real click would)?

Thanks!

**Comment by RosskoDCA** [comment]
Why is this closed? it doesn't work for me.. Am I doing something wrong?

My code:
public void onValueSelected(Entry e, int dataSetIndex, Highlight h) {
  ...

   circle.highlightValues(null);
 ....
}

and still after clicking on a piece of chart is selected

**Comment by gjudkins** [comment]
Yeah, this shouldn't be closed.  It is still a bug.  The slice is still selected, even though it isn't hilighted

**Comment by prithsharma** [comment]
Was this really solved?
After selecting a pie slice(let's say with `xIndex` 1) programmatically, a tap on the same slice triggers an `onValueSelected` event(with `xIndex` 1) instead of the `onNothingSelected` event.
Am I missing something here?

**Comment by prithsharma** [comment]
As far as I can tell in the commit referenced above, the fix for updating `lastHighlighted` was done only for programmatically DESELECTING values[by calling highlightValues(null)] - [here](https://github.com/PhilJay/MPAndroidChart/commit/19a0e03efa78fd056bda1ede639a4639e56a5148#diff-32f88011ddc3ecf11b16e506fbb5feb6R483)
The same would need to be done for SELECTING values programmatically. `lastHighlighted` doesn't get updated when a value is selected programmatically and thus subsequent tap on the same value triggers an `onValueSelected` event.

**Comment by milifili** [comment]
I have the same problem with bubble chart. I think an update needed for bubble chart as well.

**Comment by shining-cat** [comment]
Hello, same problem here on Barchart (with groupBars)
calling `highlightValues(null);` correctly update the unlightened state for the bar, 
but next touch on same bar triggers `onNothingSelected()` instead of `onValueSelected(Entry e, Highlight h)`

I found no simple way to highlight all bars on an indetical xValue, and had to highlight them one by one by hand...(for example, say I want all the bars for year 2018 to highlight when user touch any of the bars at this xValue)

Maybe the listener could somehow have a notion of what has been given to the chart as groupBars?

**Comment by estrnod** [comment]
This is also a problem for me, on both pie and bar charts. Tapping on one section in my code shows a popup.  Tapping on it again does not until the same earlier one is manually deselected.  It would be great if there were a way to programmatically deselect the section when I am done with it so that the user can tap any section for more info and not have to tap twice sometimes to get it.

**Comment by mh-** [comment]
A possible workaround (as shown  here: https://stackoverflow.com/a/37530933/8235663):
- in onValueSelected(Entry e, Highlight h): store e, h in global variables entry, highlight.
- in onNothingSelected(): call onValueSelected() with these values entry, highlight.

With this workaround, when onNothingSelected() is called every 2nd tap on the same entry, it will in turn call onValueSelected() with the desired values.

**Comment by estrnod** [comment]
Thank you! Adding this to the chart creation routine worked for me, in both pie charts and bar charts:

        chart.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View v, MotionEvent event) {
                // This allows clicking twice on same selection to show the popup again
                chart.getOnTouchListener().setLastHighlighted(null);
                chart.highlightValues(null);
                return false;
            }
        });
