### ISSUE TITLE
Add OHLC chart type

### ISSUE THREAD

**Issue by MGaetan89** [PhilJay/MPAndroidChart#751]
The OHLC (Open-High-Low-Close) chart is an other way to display a candlestick.
http://stockcharts.com/school/doku.php?id=chart_school:overview:technical_analysis_4

I'm not sure if I know enough of your library yet, but if you are interested in including this, I can give it a try and send a PR.

**Comment by PhilJay** [comment]
Honestly I am not that good with the different financial charts, but what exactly is the difference between the current candlestick and an OHCL chart?

**Comment by AlBirdie** [comment]
OHLC is just a different display of a candlestick. You can check my MPAndroidChart fork for an OHLC renderer; https://github.com/AlBirdie/MPAndroidChart

Note the the fork itself isn't necessarily new, which is why the renderer doesn't include buffering, but adapting it to use a LineBuffer shouldn't be a straightforward task.

**Comment by MGaetan89** [comment]
As @AlBirdie said, it is just an alternative representation of the classic candle stick. Some people prefer to use this view rather than candle stick.

**Comment by MGaetan89** [comment]
A reason why it was closed?
