### ISSUE TITLE
Custom labels over entries instead of their values

### ISSUE THREAD

**Issue by goshki** [PhilJay/MPAndroidChart#820]
Is it possible to attach custom text labels to each entry in a given dataset?

**Comment by TR4Android** [comment]
@goshki You can use a custom [`ValueFormatter`](https://github.com/PhilJay/MPAndroidChart/wiki/The-ValueFormatter-interface) to change the `String` displayed above the entry. Depending on what exactly you want to achieve you can either just format the value or provide another `String`. Unfortunately it doesn't provide the entry index though, so if you need that it'll get complex.

**Comment by goshki** [comment]
Good point. But I can pass the index in "data" field, right?

**Comment by goshki** [comment]
Good point. Unfortunately the label I'd like to apply is index-dependent.

**Comment by TR4Android** [comment]
@goshki Ok, then you could try this (you'll have to clone or fork the project):
1. Clone or fork this project and include that instead of the Jitpack version
2. Search for `getFormattedValue` (see [Github search results](https://github.com/PhilJay/MPAndroidChart/search?utf8=%E2%9C%93&q=getFormattedValue+path%3AMPChartLib&type=Code)): you can then change the occurrences in `ValueFormatter`s to accept `Entry` instead of `float value` and the occurrences in `Renderer`s to pass the `Entry`. (Only in MPChartLib folder)
3. Then you can write your custom formatter that has access to the complete `Entry`

Normally I would consider doing it myself and opening a pull request, but I'm short in time. Passing the `Entry` definitely allows for more flexible formatting.

**Comment by paamand** [comment]
@goshki : I had the same issue. Solved it by defining a IValueFormatter:
```
myDataset.setValueFormatter(new IValueFormatter() {
    @Override
    public String getFormattedValue(float value, Entry entry, int dataSetIndex, ViewPortHandler viewPortHandler) {
        int idx = myData.getDataSetByIndex(dataSetIndex).getEntryIndex(entry);
        ...
    }
};
```
