### ISSUE TITLE
How to create this chart using Horizontal Bar Chart

### ISSUE THREAD

**Issue by macpraveen** [PhilJay/MPAndroidChart#871]
I am trying to create the following chart using horizontal bar chart.
![Chart]
(http://i.stack.imgur.com/k85YE.png)

But the y-axis max value does not seem to be suitable. So just wanted to know whether we can create this type of chart.

**Comment by petrusgomes** [comment]
I don't think this is an "issue". You should ask this on stackoverflow:
https://stackoverflow.com/search?q=mpandroidchart

If you do, I can help with more details.

But you can use a StackedBar, like the one in the demo. Use HorizontalBarChart instead of BarChart.
https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/StackedBarActivity.java

The 100% will be:
absoluteTotal - absoluteValueOf(64%)
And I think you could use the ValueFormatter to print as 100% instead of the absolute value.
